#!/bin/bash

cd /root/alx-system_engineering-devops

mkdir 0x01-shell_permissions

cd 0x01-shell_permissions

echo "0x01-shell_permissions">README.md



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 0-iam_betty

echo -e "#!/bin/bash\nsu betty">0-iam_betty

chmod u+x 0-iam_betty



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 1-who_am_i

echo -e "#!/bin/bash\nid -un">1-who_am_i

chmod u+x 1-who_am_i



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 2-groups

echo -e "#!/bin/bash\ngroups">2-groups

chmod u+x 2-groups



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 3-new_owner

echo -e "#!/bin/bash\nsudo chown betty hello">3-new_owner

chmod u+x 3-new_owner



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 4-empty

echo -e "#!/bin/bash\ntouch hello">4-empty

chmod u+x 4-empty



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 5-execute

echo -e "#!/bin/bash\nchmod 744 hello">5-execute

chmod u+x 5-execute



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 6-multiple_permissions

echo -e "#!/bin/bash\nchmod u+x,g+x,o+r hello">6-multiple_permissions

chmod u+x 6-multiple_permissions



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 7-everybody

echo -e "#!/bin/bash\nchmod ugo+x hello">7-everybody

chmod u+x 7-everybody



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 8-James_Bond

echo -e "#!/bin/bash\nchmod 007 hello">8-James_Bond

chmod u+x 8-James_Bond



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 9-John_Doe

echo -e "#!/bin/bash\nchmod 753 hello">9-John_Doe

chmod u+x 9-John_Doe



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 10-mirror_permissions

echo -e "#!/bin/bash\nchmod --reference=olleh hello">10-mirror_permissions

chmod u+x 10-mirror_permissions



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 11-directories_permissions

echo -e "#!/bin/bash\nchmod -R +111 */">11-directories_permissions

chmod u+x 11-directories_permissions



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 12-directory_permissions

echo -e "#!/bin/bash\nmkdir -m 751 my_dir">12-directory_permissions

chmod u+x 12-directory_permissions



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 13-change_group

echo -e "#!/bin/bash\nchgrp school hello">13-change_group

chmod u+x 13-change_group



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 100-change_owner_and_group

echo -e "#!/bin/bash\nchown vincent:staff *">100-change_owner_and_group

chmod u+x 100-change_owner_and_group



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 101-symbolic_link_permissions

echo -e "#!/bin/bash\nchown -h vincent:staff _hello">101-symbolic_link_permissions

chmod u+x 101-symbolic_link_permissions



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 102-if_only

echo -e "#!/bin/bash\nchown --from=guillaume betty hello">102-if_only

chmod u+x 102-if_only



cd /root/alx-system_engineering-devops/0x01-shell_permissions

touch 103-Star_Wars

echo -e "#!/bin/bash\ntelnet towel.blinkenlights.nl">103-Star_Wars

chmod u+x 103-Star_Wars



/root/alx-system_engineering-devops/git
