#!/bin/bash

cd   /root/alx-system_engineering-devops/0x03-shell_variables_expansions

echo -e "#!/bin/bash\necho \"hello $USER\"">1-hello_you

chmod u+x 1-hello_you

/root/alx-system_engineering-devops/git
