#!/bin/bash

cd   /root/alx-system_engineering-devops/0x03-shell_variables_expansions

echo -e "#!/bin/bash\necho \$PATH | tr ':' '\n' | wc -l">3-paths

chmod u+x 3-paths

/root/alx-system_engineering-devops/git
